import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { cn } from "@/lib/utils";

const jakarta = Plus_Jakarta_Sans({
  weight: ["500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "home.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`bg-slate-100`, jakarta.className)}>
        {children}
        {/* <Link
          className="sticky mt-10 bottom text-slate-500 dark:text-slate-400"
          href="https://www.flaticon.com/free-icons/estate"
          title="estate icons"
        >
          Estate icons created by iconset.co - Flaticon
        </Link> */}
      </body>
    </html>
  );
}
